// Generated by CoffeeScript 1.6.3
(function() {
  var LightbotBot;

  module.exports = LightbotBot = (function() {
    function LightbotBot(x, y, dir, color) {
      this.x = x;
      this.y = y;
      this.dir = dir;
      this.color = color != null ? color : null;
    }

    LightbotBot.prototype.state = function() {
      var _ref, _ref1;
      return [this.x, this.y, (_ref = this.dir) != null ? _ref : 0, (_ref1 = this.color) != null ? _ref1 : 'none'].join(',');
    };

    LightbotBot.prototype.turnRight = function() {
      return this.dir = (this.dir + 1) % 4;
    };

    LightbotBot.prototype.turnLeft = function() {
      return this.dir = (this.dir - 1) % 4;
    };

    LightbotBot.prototype.moveTo = function(x, y) {
      this.x = x;
      this.y = y;
    };

    return LightbotBot;

  })();

}).call(this);
