// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    Game: require('./game'),
    Bot: require('./bot'),
    Program: require('./program'),
    Instruction: require('./instruction'),
    Square: require('./square'),
    N: 0,
    E: 1,
    S: 2,
    W: 3
  };

}).call(this);
