// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    Game: require('./game'),
    Bot: require('./bot'),
    Program: require('./program'),
    Instruction: require('./instruction'),
    Square: require('./square')
  };

}).call(this);
