// Generated by CoffeeScript 1.6.3
(function() {
  var LightbotInstruction, actions, colors,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  actions = ['forward', 'right', 'left', 'jump', 'bulb', 'p1', 'p2', 'return'];

  colors = ['green', 'red'];

  module.exports = LightbotInstruction = (function() {
    function LightbotInstruction(action, color) {
      var _ref, _ref1;
      this.action = action;
      this.color = color != null ? color : null;
      if (_ref = this.action, __indexOf.call(actions, _ref) < 0) {
        throw new Error("invalid action: " + this.action);
      }
      if ((this.color != null) && (_ref1 = !this.color, __indexOf.call(colors, _ref1) >= 0)) {
        throw new Error("invalid color: " + this.color);
      }
    }

    LightbotInstruction.prototype.draw = function() {
      var line;
      line = this.action;
      if (this.color) {
        line = "[" + (this.color === 'red' ? 31 : 32) + "m" + line + "[0m";
      }
      return console.log(line);
    };

    return LightbotInstruction;

  })();

}).call(this);
