// Generated by CoffeeScript 1.6.3
(function() {
  var LightbotProgram;

  module.exports = LightbotProgram = (function() {
    function LightbotProgram(procs, cur_proc, pc) {
      this.procs = procs;
      this.cur_proc = cur_proc != null ? cur_proc : 'main';
      this.pc = pc != null ? pc : 0;
    }

    LightbotProgram.prototype.state = function() {
      return "" + this.cur_proc + "[" + this.pc + "]";
    };

    LightbotProgram.prototype.next = function() {
      return this.procs[this.cur_proc][this.pc];
    };

    LightbotProgram.prototype.increment = function() {
      return this.pc++;
    };

    LightbotProgram.prototype.callProc = function(proc) {
      this.cur_proc = proc;
      return this.pc = 0;
    };

    return LightbotProgram;

  })();

}).call(this);
