// Generated by CoffeeScript 1.6.3
(function() {
  var LightbotProgram;

  module.exports = LightbotProgram = (function() {
    function LightbotProgram(procs, cur_proc, pc) {
      this.procs = procs;
      this.cur_proc = cur_proc != null ? cur_proc : 'main';
      this.pc = pc != null ? pc : 0;
      this.callers = [];
    }

    LightbotProgram.prototype.state = function() {
      return "" + this.cur_proc + "[" + this.pc + "]";
    };

    LightbotProgram.prototype.next = function() {
      return this.procs[this.cur_proc][this.pc];
    };

    LightbotProgram.prototype.increment = function() {
      var _ref, _results;
      this.pc++;
      _results = [];
      while (this.callers.length && !this.next()) {
        _ref = this.callers.pop(), this.cur_proc = _ref[0], this.pc = _ref[1];
        _results.push(this.pc++);
      }
      return _results;
    };

    LightbotProgram.prototype.returnFromProc = function() {
      var _ref;
      if (this.callers.length) {
        _ref = this.callers.pop(), this.cur_proc = _ref[0], this.pc = _ref[1];
        return this.pc++;
      } else {
        return this.pc = this.procs[this.cur_proc].length - 1;
      }
    };

    LightbotProgram.prototype.callProc = function(p) {
      this.callers.push([this.cur_proc, this.pc]);
      this.cur_proc = p;
      return this.pc = 0;
    };

    return LightbotProgram;

  })();

}).call(this);
