// Generated by CoffeeScript 1.6.3
(function() {
  var LightbotSquare;

  module.exports = LightbotSquare = (function() {
    function LightbotSquare(_arg) {
      var _ref;
      _ref = _arg != null ? _arg : {}, this.color = _ref.color, this.goal = _ref.goal, this.elev = _ref.elev, this.tagged = _ref.tagged, this.lift = _ref.lift, this.warp = _ref.warp;
      if (this.elev == null) {
        this.elev = 0;
      }
    }

    return LightbotSquare;

  })();

}).call(this);
